export const MAIN_ACTION_TYPE = 'MAIN_ACTION_TYPE'

export const URUBUTO_AUTHORIZATION = 'URUBUTO_AUTHORIZATION'
export const URUBUTO_AUTHORIZATION_SUCCESS = 'URUBUTO_AUTHORIZATION_SUCCESS'
export const URUBUTO_AUTHORIZATION_ERROR = 'URUBUTO_AUTHORIZATION_ERROR'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
export const GET_SIGNED_USER = 'GET_SIGNED_USER'
export const GET_SIGNED_USER_SUCCESS = 'GET_SIGNED_USER_SUCCESS'
export const GET_SIGNED_USER_ERROR = 'GET_SIGNED_USER_ERROR'


export const ACTION_TYPE = {
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_ERROR,
    LOGOUT,
    URUBUTO_AUTHORIZATION,
    URUBUTO_AUTHORIZATION_SUCCESS,
    URUBUTO_AUTHORIZATION_ERROR,
    LOGOUT_SUCCESS,
    GET_SIGNED_USER,
    LOGOUT_ERROR,
}